### ISSUE TITLE
Rename the update command's --downgrade flag to --force

### ISSUE THREAD

**Issue by velovix** [aotuai/brainframe_cli#9]
There are situations, like when a customer is participating in a beta release, where it may be necessary to re-pull the latest available version of BrainFrame. Right now, they have to pass the `--downgrade` flag even though this is, if anything, an upgrade operation. I think the flag should be called `--force`, which covers both the case of a forced downgrade, and of a forced re-pull of a release.

**Comment by velovix** [comment]
@apockill Does this sound reasonable? This was inspired by watching you go through this and seeing how awkward it was.

**Comment by apockill** [comment]
Yes, I'm down!
